language: python
python:
  - "3.5.2"
before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
    - sudo apt-get update -q
    - sudo apt-get install libgdal-dev
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal
    - pip3 install gdal==2.2.2
script:
    - python3 -m"nose" tests/
