# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_interlis.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Interlis(object):
    def setupUi(self, Interlis):
        Interlis.setObjectName("Interlis")
        Interlis.resize(545, 321)
        self.gridLayout_2 = QtWidgets.QGridLayout(Interlis)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Interlis)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.transfertab = QtWidgets.QWidget()
        self.transfertab.setObjectName("transfertab")
        self.gridLayout = QtWidgets.QGridLayout(self.transfertab)
        self.gridLayout.setObjectName("gridLayout")
        self.mImdGroupBox = QgsCollapsibleGroupBoxBasic(self.transfertab)
        self.mImdGroupBox.setEnabled(True)
        self.mImdGroupBox.setProperty("collapsed", True)
        self.mImdGroupBox.setObjectName("mImdGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mImdGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mModelFileButton = QtWidgets.QPushButton(self.mImdGroupBox)
        self.mModelFileButton.setObjectName("mModelFileButton")
        self.gridLayout_3.addWidget(self.mModelFileButton, 0, 3, 1, 1)
        self.mImportEnumsButton = QtWidgets.QPushButton(self.mImdGroupBox)
        self.mImportEnumsButton.setEnabled(False)
        self.mImportEnumsButton.setObjectName("mImportEnumsButton")
        self.gridLayout_3.addWidget(self.mImportEnumsButton, 3, 2, 1, 1)
        self.mModelLineEdit = QtWidgets.QLineEdit(self.mImdGroupBox)
        self.mModelLineEdit.setObjectName("mModelLineEdit")
        self.gridLayout_3.addWidget(self.mModelLineEdit, 0, 1, 1, 2)
        self.mModelFileLabel = QtWidgets.QLabel(self.mImdGroupBox)
        self.mModelFileLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mModelFileLabel.setObjectName("mModelFileLabel")
        self.gridLayout_3.addWidget(self.mModelFileLabel, 0, 0, 1, 1)
        self.mCreateSchemaButton = QtWidgets.QPushButton(self.mImdGroupBox)
        self.mCreateSchemaButton.setEnabled(False)
        self.mCreateSchemaButton.setObjectName("mCreateSchemaButton")
        self.gridLayout_3.addWidget(self.mCreateSchemaButton, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.mImdGroupBox, 2, 0, 1, 5)
        self.mDataFileLabel = QtWidgets.QLabel(self.transfertab)
        self.mDataFileLabel.setObjectName("mDataFileLabel")
        self.gridLayout.addWidget(self.mDataFileLabel, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.cbDbConnections = QtWidgets.QComboBox(self.transfertab)
        self.cbDbConnections.setEnabled(False)
        self.cbDbConnections.setObjectName("cbDbConnections")
        self.gridLayout.addWidget(self.cbDbConnections, 4, 3, 1, 2)
        self.mModelAutoLoadCheckBox = QtWidgets.QCheckBox(self.transfertab)
        self.mModelAutoLoadCheckBox.setChecked(True)
        self.mModelAutoLoadCheckBox.setObjectName("mModelAutoLoadCheckBox")
        self.gridLayout.addWidget(self.mModelAutoLoadCheckBox, 1, 0, 1, 2)
        self.mDataFileButton = QtWidgets.QPushButton(self.transfertab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mDataFileButton.sizePolicy().hasHeightForWidth())
        self.mDataFileButton.setSizePolicy(sizePolicy)
        self.mDataFileButton.setObjectName("mDataFileButton")
        self.gridLayout.addWidget(self.mDataFileButton, 0, 4, 1, 1)
        self.mQgisLayer = QtWidgets.QCheckBox(self.transfertab)
        self.mQgisLayer.setChecked(True)
        self.mQgisLayer.setObjectName("mQgisLayer")
        self.gridLayout.addWidget(self.mQgisLayer, 4, 0, 1, 1)
        self.mDataLineEdit = QtWidgets.QLineEdit(self.transfertab)
        self.mDataLineEdit.setObjectName("mDataLineEdit")
        self.gridLayout.addWidget(self.mDataLineEdit, 0, 1, 1, 3)
        self.mDestQgisLayerCheckBox = QtWidgets.QLabel(self.transfertab)
        self.mDestQgisLayerCheckBox.setObjectName("mDestQgisLayerCheckBox")
        self.gridLayout.addWidget(self.mDestQgisLayerCheckBox, 4, 2, 1, 1)
        self.tabWidget.addTab(self.transfertab, "")
        self.settingstab = QtWidgets.QWidget()
        self.settingstab.setObjectName("settingstab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.settingstab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.settingstab)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.cbResetData = QtWidgets.QCheckBox(self.frame_2)
        self.cbResetData.setChecked(True)
        self.cbResetData.setObjectName("cbResetData")
        self.gridLayout_8.addWidget(self.cbResetData, 4, 1, 1, 1)
        self.cbStrokeCurve = QtWidgets.QCheckBox(self.frame_2)
        self.cbStrokeCurve.setChecked(True)
        self.cbStrokeCurve.setObjectName("cbStrokeCurve")
        self.gridLayout_8.addWidget(self.cbStrokeCurve, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 6, 1, 1, 1)
        self.mIlisMetaUrlLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.mIlisMetaUrlLineEdit.setObjectName("mIlisMetaUrlLineEdit")
        self.gridLayout_8.addWidget(self.mIlisMetaUrlLineEdit, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 1, 0, 1, 1)
        self.cbSkipFailures = QtWidgets.QCheckBox(self.frame_2)
        self.cbSkipFailures.setChecked(True)
        self.cbSkipFailures.setObjectName("cbSkipFailures")
        self.gridLayout_8.addWidget(self.cbSkipFailures, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 2, 0, 1, 1)
        self.mRepoUrlLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.mRepoUrlLineEdit.setEnabled(False)
        self.mRepoUrlLineEdit.setObjectName("mRepoUrlLineEdit")
        self.gridLayout_8.addWidget(self.mRepoUrlLineEdit, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.settingstab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Interlis)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 2, 1, 1)
        self.mImportButton = QtWidgets.QPushButton(Interlis)
        self.mImportButton.setEnabled(False)
        self.mImportButton.setObjectName("mImportButton")
        self.gridLayout_2.addWidget(self.mImportButton, 2, 0, 1, 1)
        self.mModelFileLabel.setBuddy(self.mModelLineEdit)
        self.mDataFileLabel.setBuddy(self.mDataLineEdit)
        self.mDestQgisLayerCheckBox.setBuddy(self.cbDbConnections)
        self.label_4.setBuddy(self.mIlisMetaUrlLineEdit)
        self.label_3.setBuddy(self.mRepoUrlLineEdit)

        self.retranslateUi(Interlis)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Interlis.accept)
        self.buttonBox.rejected.connect(Interlis.reject)
        self.mModelAutoLoadCheckBox.clicked['bool'].connect(self.mImdGroupBox.setCollapsed)
        QtCore.QMetaObject.connectSlotsByName(Interlis)

    def retranslateUi(self, Interlis):
        _translate = QtCore.QCoreApplication.translate
        Interlis.setWindowTitle(_translate("Interlis", "Interlis"))
        self.mImdGroupBox.setTitle(_translate("Interlis", "Lokales Modell"))
        self.mModelFileButton.setText(_translate("Interlis", "..."))
        self.mImportEnumsButton.setText(_translate("Interlis", "Enums importieren"))
        self.mModelFileLabel.setText(_translate("Interlis", "&IlisMeta Modell:"))
        self.mCreateSchemaButton.setText(_translate("Interlis", "DB-Tabellen anlegen"))
        self.mDataFileLabel.setText(_translate("Interlis", "&Transferfile:"))
        self.mModelAutoLoadCheckBox.setText(_translate("Interlis", "Modell automatisch laden"))
        self.mDataFileButton.setText(_translate("Interlis", "..."))
        self.mQgisLayer.setText(_translate("Interlis", "QGIS Layer"))
        self.mDestQgisLayerCheckBox.setText(_translate("Interlis", "Post&GIS:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.transfertab), _translate("Interlis", "Import"))
        self.cbResetData.setText(_translate("Interlis", "Daten ersetzen"))
        self.cbStrokeCurve.setText(_translate("Interlis", "Kurven segmentieren"))
        self.mIlisMetaUrlLineEdit.setText(_translate("Interlis", "http://interlis.sourcepole.ch/wps"))
        self.label_4.setText(_translate("Interlis", "IlisMeta Lookup:"))
        self.cbSkipFailures.setText(_translate("Interlis", "Import-Fehler überspringen"))
        self.label_3.setText(_translate("Interlis", "Model Repositories:"))
        self.mRepoUrlLineEdit.setText(_translate("Interlis", "http://models.interlis.ch/"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingstab), _translate("Interlis", "Einstellungen"))
        self.mImportButton.setText(_translate("Interlis", "Import"))

from qgis.gui import QgsCollapsibleGroupBoxBasic
